services:
  nextjs:
    image: peekaboo/nextjs
    container_name: peekaboo_nextjs
    build:
      context: ./
      args:
        NODE_DOCKER_REGISTRY: ${NODE_DOCKER_REGISTRY}
        LDAP_URL: ${LDAP_URL}
      dockerfile: Dockerfile
    environment:
      - LDAP_URL=${LDAP_URL}
      - LDAP_DC=${LDAP_DC}
    restart: always
    volumes:
      - ./.env:/app/.env:ro
    expose:
      - "3000"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: peekaboo_nginx
    restart: always
    ports:
      - "4443:4443"
      - "8180:8180"
    depends_on:
      - nextjs
      - websock
    environment:
      - SERVER_HOSTNAME=${HOSTNAME}
      - WEBSOCKET_SERVER_HOSTNAME=${WEBSOCKET_SERVER_HOSTNAME}
    volumes:
      - ./utils/certs:/etc/nginx/certs:ro
      - ./scripts/configs/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    networks:
      - backend
      - frontend

  websock:
    image: peekaboo/websock
    container_name: peekaboo_websock
    build:
      context: ./websock/
      args:
        PYTHON_DOCKER_REGISTRY: ${PYTHON_DOCKER_REGISTRY}
        PIP_CONF_PATH: ${PIP_CONF_PATH}
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./websock/websocket_token_source.txt:/app/websocket_token_source.txt:ro
      - ./.env:/app/.env:ro
    ports:
      - "60800"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
