name: peek-a-boo

services:
  ui:
    image: ghcr.io/system-b90/peek-a-boo/nextjs:${PEEKABOO_VERSION:-latest}
    container_name: peekaboo-ui
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../.env:/app/.env:ro
    expose:
      - "3000"
    networks:
      - backend

  proxy:
    image: nginx:alpine
    container_name: peekaboo-proxy
    restart: always
    ports:
      - "${PEEKABOO_BIND_IP:-0.0.0.0}:${PEEKABOO_HTTPS_PORT:-443}:443"
      - "${PEEKABOO_BIND_IP:-0.0.0.0}:${PEEKABOO_HTTP_PORT:-80}:80"
    depends_on:
      - ui
      - vnc-bridge
    env_file:
      - ../.env
    environment:
      - SERVER_HOSTNAME=${HOSTNAME}
      - WEBSOCKET_SERVER_HOSTNAME=${WEBSOCKET_SERVER_HOSTNAME}
    volumes:
      - ../utils/certs:/etc/nginx/certs:ro
      - ../scripts/configs/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    networks:
      - backend
      - frontend

  vnc-bridge:
    image: ghcr.io/system-b90/peek-a-boo/websock:${PEEKABOO_VERSION:-latest}
    container_name: peekaboo-vnc-bridge
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../websock/websocket_token_source.txt:/app/websocket_token_source.txt:ro
      - ../.env:/app/.env:ro
    ports:
      - "60800"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
