name: Build Docker Image (Artifact)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Create .env file inside Action runner (Compose auto-loads it)
      - name: Load .env into workflow environment
        run: |
          if [ -f .env ]; then
            echo "Loading .env..."
            cat .env >> $GITHUB_ENV
          else
            echo ".env does not exist, skipping."
          fi

      # 3. Build using docker-compose
      - name: Build with docker-compose
        run: |
          docker compose build

      # 4. Save built image(s)
      - name: Save Docker image as tarball
        run: |
          mkdir -p artifacts
          
          docker save "peekaboo/peekaboo_nextjs" | gzip > artifacts/peekaboo_nextjs.tar.gz
          docker save "peekaboo/peekaboo_websock" | gzip > artifacts/peekaboo_websock.tar.gz

      # 5. Upload artifact
      - name: Upload NextJS Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: peekaboo_nextjs.tar.gz
          path: artifacts/peekaboo_nextjs.tar.gz
          retention-days: 1
      
          # 6. Upload artifact
      - name: Upload websock Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: peekaboo_websock.tar.gz
          path: artifacts/peekaboo_websock.tar.gz
          retention-days: 1
